name: run-aosd-check

on:
  push:
    branches:
      - m.reiter/aosd
      - k.vasileuskaya/aosd
  workflow_dispatch:

jobs:
  ort:
    name: Check AOSD with ort
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v5

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run GitHub Action for ORT
        uses: oss-review-toolkit/ort-ci-github-action@v1.1.0
        with:
          ort-cli-args: >
            -P ort.scanner.skipExcluded=true
          ort-cli-report-args: '-f AOSD2.1 -o results/reports/aosd2.1'